//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApiSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public long IdCarrito { get; set; }
        public long IdUsuario { get; set; }
        public long IdProducto { get; set; }
        public System.DateTime FechaCarrito { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
