//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApiSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public long IdReserva { get; set; }
        public long IdServicio { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal PrecioPago { get; set; }
        public string Cliente { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
